#!/usr/bin/python3 # -*- coding: utf-8 -*- 3 al 5 obligado, 6 es el prompt, 9 constructor, 10 super, 11 llama la ventana, 12 es el boton, con evento, conectar, conectado con el metodo saludar que es un metodo, la linea 15 establece en el labSalida.set text el texto, haciendo txtpersona.text, en el 16 hace el promtp

import sys 
from PyQt5 import uic
from PyQt5.QtWidgets import QMainWindow, QApplication
from PyQt5.QtWidgets import QMessageBox 
import math


class Example(QMainWindow):
    
    divisores=2
    siguiente=0
    resultados =[]
    
    def __init__(self):
        super().__init__()
        uic.loadUi("ventanita.ui",self)
        self.btnCalcular.clicked.connect(self.mostrar)
        
        
    def mostrar(self):
        self.labSalida.setText("el resultado es"+self.calcularPrimo(int(self.txtRangodos.text()),int(self.txtRangouno.text())))
        #QMessageBox.about(self, "Saludo", "Hola "+self.txtPersona.text())

    def calcularPrimo(self,final,inicial):
        divisores=2
        resultados =[]
        for i in range(0,final-inicial+1):
            numero=inicial+i
            raizcadauno=math.sqrt(numero)
            if (divisores>math.sqrt(numero)):
                primo=1
            while (divisores<=raizcadauno):
                primo=1
                if numero%divisores == 0:
                    primo=0
                    break
                divisores=divisores + 1
            divisores=2
            if (primo == 1):
                resultados.append(inicial+i)
        
        cadena = " ".join(str(resultados))
        return cadena

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = Example()
    ex.show()
    sys.exit(app.exec_())
